### PR TITLE
Default highest quality && Add 5s timeout for fetching a webpage with failing retry

### PR DESCRIPTION
**Pull request by ShenHongFei**
Default highest quality (112)
Add 5s timeout for fetching a webpage with failing retry

### CODE REVIEW

**Comment by kamikat** [comment]
Thanks for opening the PR, but CI complains about code formatting. It would be nice if you can fix these lint errors.

**Comment by ShenHongFei** [comment]
Formatting problems are solved and test passed somtimes on my local machine(sometimes not), but unfortunately it didn't pass in Travis CI (Probably networking problems?). Could you help?
log:
```
> tap test.js

test.js ............................................. 11/11 22s
total ............................................... 11/11

  11 passing (22s)

  ok
```

**Comment by kamikat** [comment]
Let's see if it works on master build :laughing:

**Comment by ShenHongFei** [comment]
haha, it passed, AC.

**Comment by kamikat** [comment]
¯\\_(ツ)_/¯

**Pull request merged**
